class Const():
    TYPE_WEEKLY_DATA = 'weeklyData'
    TYPE_WEEKLY_AVG_DATA = 'weeklyAvgData'
    PATH_WEEKLY_DATA ='weeklyData.xlsx'
    PATH_WEEKLY_AVG_DATA = 'weeklyAvgData.xlsx'

    QUERY_TYPE_VERSIONS='VERSIONS'
    QUERY_TYPE_SUBTYPES='SUBTYPES'
    QUERY_TYPE_SUCCESSRATIO='SUCCESSRATIO'
    QUERY_TYPE_ERRORCODE='ERRORCODE'
    pass